attach(cars)
cars
min(cars[2])
min(cars[4])
min(cars$Miles.per.gallon)
max(cars[3])
max(cars$Horsepower)
mean(cars$Displacement)
mean(cars[["Weight"]])
median(cars$Gears)
sapply(cars[5],sd)
sd(cars$Displacement)
quantile(cars$Displacement, c(.0, .25, .50, .75, .100))
summary(cars)
boxplot(Horsepower)