---
title: "Metaheuristics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries

```{r}
library(GenSA)
library(ggplot2)
library(GA)
library(dplyr)
```

# Portfolio Optimization

```{r}
library("quantmod")
tickers <- c("GE", "IBM", "GOOG", "AMZN", "AAPL")
getSymbols(tickers, from = "2004-12-01", to = "2018-10-27")
P <- NULL
for(ticker in tickers) {
 tmp <- Cl(to.monthly(eval(parse(text = ticker))))
 P <- cbind(P, tmp)
}
colnames(P) <- tickers
R <- diff(log(P))
R <- R[-1,]
mu <- colMeans(R)
sigma <- cov(R)
library("PerformanceAnalytics")
pContribCVaR <- ES(weights = rep(0.2, 5), method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)$pct_contrib_ES
obj <- function(w) {
 fn.call <<- fn.call + 1
 if (sum(w) == 0) { w <- w + 1e-2 }
 w <- w / sum(w)
 CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
 tmp1 <- CVaR$ES
 tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
 out <- tmp1 + 1e3 * tmp2
 return(out)
}
```

# Using GenSA for Simulated Annealing

```{r}
set.seed(1234)
fn.call <<- 0
out.GenSA <- GenSA(fn = obj, lower = rep(0, 5), upper = rep(1, 5), control = list(smooth = FALSE, max.call = 3000))
fn.call.GenSA <- fn.call
out.GenSA$value
out.GenSA$counts
cat("GenSA call functions", fn.call.GenSA, "times.\n")
wstar.GenSA <- out.GenSA$par
wstar.GenSA <- wstar.GenSA / sum(wstar.GenSA)
rbind(tickers, round(100 * wstar.GenSA, 2))
100 * (sum(wstar.GenSA * mu) - mean(mu))
```

# Rastrigin function

```{r}
Rastrigin <- function(x1, x2)
{
  20 + x1^2 + x2^2 - 10*(cos(2*pi*x1) + cos(2*pi*x2))
}

x1 <- x2 <- seq(-5.12, 5.12, by = 0.1)
f <- outer(x1, x2, Rastrigin)
persp3D(x1, x2, f, theta = 50, phi = 20, color.palette = bl2gr.colors)
```

# Using GA for Genetic Algorithm

```{r}
gap <- ga(type = "real-valued",fitness=function(w) - Rastrigin(w[1],w[2]),lower=rep(0,5), upper=rep(1,5), popSize = 50, maxiter = 100)
summary(gap)
plot(gap)
```

# Comparing GA and SA performance

```{r}
result <- matrix(c( 0.10,21.42,29.17,21.39,8.91,19.11,-0.042,0.012,0.008,0.469,0.439,0.371),nrow=6,ncol=2)
colnames(result) <- c("Simulated Annealing","Genetic Algorithm")
rownames(result) <- c("Fitness function value","x1","x2","x3","x4","x5")
result
```




# Question 2 - Optimal parameters for regression 

```{r}
X <- c(61,63,67,69,70,74,76,81,86,91,95,97)
Y <- c(4.28,4.08,4.42,4.17,4.48,4.3,4.82,4.7,5.11,5.13,5.64,5.56)
fun = function(x,y) { (sin(10*x)*cos(10*y)+2)/sqrt(x^4+y^4+1) } 
obj = function(z)
{
 fn.call <<- fn.call + 1
 SSYY=sum((Y-mean(Y))^2)
 SSXY=sum((X-mean(X))*(Y-mean(Y)))
 SSX=sum((X-mean(X))^2)
 b1= SSXY/SSX
 b0=mean(Y)-b1*mean(X)
 Y_Estimated=X*b1+b0
 Residuals= Y-Y_Estimated
 SSE=sum((Residuals -mean(Residuals))^2)
 out <- SSE
 return(out)
}
```

# Using GenSA

```{r}
set.seed(1234)
fn.call <<- 0
out.GenSA <- GenSA(fn = obj, lower = rep(0, 2), upper = rep(5, 2), control = list(smooth = FALSE, max.call = 3000))
fn.call.GenSA <- fn.call
out.GenSA$value
out.GenSA$counts
cat("GenSA call functions", fn.call.GenSA, "times.\n")
```

# Using GA

```{r}
gap <- ga(type = "real-valued", fitness=obj, lower=rep(0,2), upper=rep(5,2), popSize = 50, maxiter = 100)
summary(gap)
plot(gap)
```

# Plot for Regression

```{r}
x=seq(-5,5,length=50)
y=seq(-5,5,length=50) 
z=outer(x,y,fun) 
 persp3D(x, y, z, phi = 0, theta = 45,
  xlab = "X", ylab = "Y",
  main = "Optimal Parameters for Regression",
  color.palette = bl2gr.colors
)
filled.contour(x, y, z, color.palette = bl2gr.colors)
```

# Optimal Regression line

```{r}
plot(X,Y,xlim=c(60, 100),xlab="Number of Passengers", ylab="Cost ($1000)", col="blue")
abline(lsfit(X, Y),col = "red")

```
